# -*- coding: utf-8 -*-
"""FDM_solver.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rj06mX1Z15bLdDuRtmGx4kLKCVmWlRx_

Today is a beautiful day.
"""

import numpy as np
import math as ma
import matplotlib.pyplot as plt
from scipy.linalg import eigh
import scipy.constants as cnst

eV = cnst.eV
h_c = cnst.hbar
m_e = cnst.m_e

 #constant term

params = {}

"""-ℏ^2 /2m (d²Ψ/dt²) + V(x)Ψ = EΨ"""

# potential
def potential(x, params):
  #write according to potential you need
  return 0

#E*ψ[i] = P*(2*ψ[i] - ψ[i+1] - ψ[i-1])/(a**2) + V[i]*ψ[i]

#Solver
def fdm_schrodinger(x_s, x_e, N, potential, params):
  x = np.linspace(x_s, x_e, N-1) * 1e-9
  a = (x_e-x_s)/N * 1e-9
  m = params.get('m',m_e)
  P = (h_c**2)/(2*m)
  V = potential(x, params)

  main_diagonal = 2*P/(a**2) + V
  off_diagonal = -P/(a**2)* np.ones(N-2)
  H = np.diag(main_diagonal) + np.diag(off_diagonal, k=1) + np.diag(off_diagonal, k=-1)

  E, ψ = eigh(H)
  ψ = ψ * np.sqrt(1e-9) / np.sqrt(a)
  E = E/eV
  x= x*1e9
  return E,ψ,x

