# -*- coding: utf-8 -*-
"""QM_Shooting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kyl4ctHDVGFYHAx-4pLe4SGS1iVKkRRO
"""

import numpy as np
import scipy.constants as cnst
from scipy.integrate import solve_ivp, simpson
import matplotlib.pyplot as plt
from scipy.special import eval_hermite

eV = cnst.eV
hbar = cnst.hbar
m_e = cnst.m_e

L = 1e-9                # L = 1 nm

"""$$\frac{-\hbar^2}{2m}\frac{d^2\psi}{dx^2} + V\psi = E \psi$$ Non dimensionalising this, we get: $$\frac{d^2\Pi}{dX^2} = \frac{2mL^2(V - E)}{\hbar^2}\Pi$$ where, $\Pi = \sqrt{L}\psi$ and $X = x/L$, where $L$ is an arbitrary constant with the dimensions of length.

The normalization condition remains the same, i.e: $$\int_{-\infty}^{\infty}\left|\Pi\right|^2dX = 1$$
"""

def Find_eigenvalue(params, V, x_s = -1e1, x_e = 1e1, N = 200, E_1 = 1, dE = 0.01, rtol = 1e-6):
    x_list = np.linspace(x_s, x_e, N)
    E_2 = E_1 + dE
    atol = rtol

    def deriv(X, y, E, params, V):
        m = params.get('m', m_e)
        U = V(X, params)
        C = 2*m_e/hbar**2*L**2*eV
        return [y[1], (C*(U - E))*(m/m_e)*y[0]]

    sol_1 = solve_ivp(deriv, (x_s, x_e), [0, 1], method = 'LSODA', t_eval = x_list, rtol = rtol, atol = atol, args = (E_1, params, V))
    sol_2 = solve_ivp(deriv, (x_s, x_e), [0, 1], method = 'LSODA', t_eval = x_list, rtol = rtol, atol = atol, args = (E_2, params, V))

    if abs(sol_1.y[0][-1]) < atol:
        print(sol_1.y[0][-1])
        Pi_1_2 = sol_1.y[0]*np.conj(sol_1.y[0])
        I_1 = simpson(Pi_1_2, sol_1.t)
        Pi_1 = sol_1.y[0]/np.sqrt(I_1)
        return x_list, Pi_1, E_1

    elif abs(sol_2.y[0][-1]) < atol:
        Pi_2_2 = sol_2.y[0]*np.conj(sol_2.y[0])
        I_2 = simpson(Pi_2_2, sol_2.t)
        Pi_2 = sol_2.y[0]/np.sqrt(I_2)
        return x_list, Pi_2, E_2

    else:
        maxi = 1000
        for i in range(maxi):
            if np.sign(sol_1.y[0][-1]) != np.sign(sol_2.y[0][-1]):
                break
            E_1, sol_1 = E_2, sol_2
            E_2 += dE
            sol_2 = solve_ivp(deriv, (x_s, x_e), [0, 1], method = 'LSODA', t_eval = x_list, rtol = rtol, atol = atol, args = (E_2, params, V))

            if abs(sol_2.y[0][-1]) < atol:
                Pi_2_2 = sol_2.y[0]*np.conj(sol_2.y[0])
                I_2 = simpson(Pi_2_2, sol_2.t)
                Pi_2 = sol_2.y[0]/np.sqrt(I_2)
                return x_list, Pi_2, E_2

        else:
            raise RuntimeError(f"Failed to bracket an eigenvalue after {maxi} steps")

        E = (E_1 + E_2)/2
        sol_3 = solve_ivp(deriv, (x_s, x_e), [0, 1], method = 'LSODA', t_eval = x_list, rtol = rtol, atol = atol, args = (E, params, V))

        while abs(E - E_1) > 1e-6 and abs(E - E_2) > 1e-6:
            if np.sign(sol_3.y[0][-1]) == np.sign(sol_2.y[0][-1]):
                E_2 = E
                sol_2 = sol_3
            else:
                E_1 = E
                sol_1 = sol_3

            E = (E_1 + E_2)/2
            sol_3 = solve_ivp(deriv, (x_s, x_e), [0, 1], method = 'LSODA', t_eval = x_list, rtol = rtol, atol = atol, args = (E, params, V))

        Pi_3_2 = sol_3.y[0]*np.conj(sol_3.y[0])
        I_3 = simpson(Pi_3_2, sol_3.t)
        Pi_3 = sol_3.y[0]/np.sqrt(I_3)
        return x_list, Pi_3, E

def wave_shooting(params, V, x_s = -1e1, x_e = 1e1, N = 200, E_1 = 1, dE = 0.01, rtol = 1e-6):
  soln = {}
  for i in range(6):

    x_list, Pi, E_ans = Find_eigenvalue(params, V, x_s, x_e, N, E_1, dE, rtol)
    if i==0:
      soln["Ground State"] = {"x": x_list, "Pi": Pi, "E": E_ans}
    else:
      soln[f"Excited State {i}"] = {"x": x_list, "Pi": Pi, "E": E_ans}
    E_1 = E_ans+dE
  return soln